### ISSUE TITLE
Bits swapped in title

### ISSUE THREAD

**Issue by AshenClarity** [cthill/SNESDump#3]
![image](https://user-images.githubusercontent.com/14829722/84622255-6408a300-ae91-11ea-8ae3-3bf66d5d8e99.png)

Hi! so I threw together a cart reader based on the circuit diagram and Im having a problem where some letters are swapped when reading data, Ive been unable to successfully dump a Rom and I'm guessing its related to this problem. Any chance there are any insights as to what might be the cause?

the games in the contained image for reference are Star Fox and Super Fire Pro Wrestling

**Comment by play134** [comment]
Hello! 

I have the same problem. I double-checked the wires and continue the same way. Also tested a starfox cartridge and indicated exactly the same problem as the image you posted.

I don't know if it could be a software problem or something related to hardware. Since the software on the desktop side is not compatible with python3, need to install 2.7.15 to work. 

In relation to the dump, my nano is clone and i attached an authentic FTDI to USB on the TX and RX ports of the arduino, that way I can do the dump in hi speed, but the dump is not correct. The bits are still wrong.

I think the project is dead, we have no support.

**Comment by play134** [comment]
**UPDATE**

ok so i found the problem. The diagram is wrong with respect to the firmware. Simply change the wires D0 and D1 and make the dump. I hope it helps.

**Comment by cthill** [comment]
@play134 Thank you for the feedback. I have updated the circuit diagram.
